import React from "react";
import { DocsThemeConfig } from "nextra-theme-docs";

const config: DocsThemeConfig = {
  logo: <span className="font-bold text-xl">HUFS GSECE</span>,
  project: {
    link: "https://github.com/dokdo2013/hufs-gsece",
  },
  docsRepositoryBase: "https://github.com/dokdo2013/hufs-gsece/tree/main",
  footer: {
    text: "Generated by Nextra",
  },
  useNextSeoProps() {
    return {
      titleTemplate: "%s - HUFS GSECE",
    };
  },
};

export default config;
